# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ffgxIkVKzZOH7hUbR0cMv/uLdvWKEw7WB+f0q4AAiLbTa/6nrSUPx0craorCp9Rh
    ports:
      - 33306:3306
    networks:
      - skynet

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8181:8080
    networks:
      - skynet

networks:
  skynet: