version: '3.1'
services:
  dbincidentes:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - skynet
    ports:
      - 33306:3306

  adminerincidentes:
    image: adminer
    restart: "no"
    networks:
      - skynet
    ports:
      - 8181:8080

  correoincidentes:
    image: marooou/postfix-roundcube
    environment:
      ADMIN_USERNAME: root
      ADMIN_PASSWD: root
      DOMAIN_NAME: jorgeortega.lan
    ports:
      - 25:25
      - 8282:80
      - 110:110
      - 143:143
      - 465:465
      - 993:993
      - 995:995
    networks:
      -skynet
networks:
skynet: